VERSION="2.1.0"
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"

ACCOUNTS=["GCOHQFQZZPCRV74BU5PCMCMGIQYI4XSV5NXI5LZS3J53L7HMVSQHVTHD"]
SQ02_EASTER_EGG="Log into series 2 of Stellar Quest then visit quest.stellar.org/series2. Finally drag and drop your Stellar Quest series 2 badge PNG images onto the screen. Enjoy!"
